language: node_js

sudo: required

services:
  - docker

node_js:
  - "12"

arch:
  - amd64

os: 
  - linux

install:
  - npm install

  # Compile OpenCV
  - (cd ./utils && bash ./build.sh)

  # Separate Wasm
  - (cd ./build_wasm_test/bin && npm install)


script:
  # Run opencv's test
  - (cd ./build_wasm_test/bin && node tests.js)
  # Run opencv-wasm's test
  - npm test
